import "./globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import { Roboto_Condensed as FontSans } from "next/font/google";
import Providers from "@/components/layout/Provider";
import { Analytics } from "@vercel/analytics/react";
export const metadata: Metadata = {
  title: "Data-Nro / Shopwibu.Net",
  description: "Generated by wibusama",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <NextTopLoader showSpinner={false} />
        <Providers>{children}</Providers>
        <Analytics />
      </body>
    </html>
  );
}
